version: 2

sources:
  - name: projeto_light_house
    schema: light_house
    description: Projeto LightHouse
    tables:
      - name: categories
        columns:
          - name: category_id
            description: Chave Primária da tabela categories.
            tests:
              - unique
              - not_null
      - name: customers
      - name: employee_territories
      - name: employees
      - name: order_details
      - name: orders
      - name: products
      - name: region
      - name: shippers
      - name: suppliers
      - name: territories
      - name: us_states